apiVersion: v1
kind: Pod
metadata:
  name: proje8
spec:
  containers:
  - name: main
    image: quay.io/aminrf/proje:v0.0.6
    command:
    - "bash"
    - "-c"
    - "cp ./examples/SimpleStorage.sol ./input/contract.sol;
    export PYTHONPATH=$PWD;
    rm -rf ./input/mutants || true;
    mkdir ./input/mutants;
    python3 universalmutator/genmutants.py input/contract.sol --mutantDir ./input/mutants;
    python3 -u script.py;
    sleep infinity"
    resources:
      requests:
        cpu: 1000m
        memory: 2000Mi
      limits:
        cpu: 1000m
        memory: 2000Mi